version: "3"
services:

    web:
        image: nginx:latest
        container_name: webtrocas_web
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
        depends_on:
            - php
        deploy:
            restart_policy:
                condition: on-failure
    php:
        image: lamasbr/php:7.1-fpm
        container_name: webtrocas_php
        volumes:
            - ./code:/code
        depends_on:
            - db
        deploy:
            restart_policy:
                condition: on-failure
    db:
        image: mysql:latest
        container_name: webtrocas_db
        ports:
            - "3306:3306"
        #volumes:
        #    - ./data/mysql:/var/lib/mysql
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            MYSQL_DATABASE: webtrocas
            MYSQL_ROOT_PASSWORD: webtrocas
            MYSQL_USER: webtrocas
            MYSQL_PASSWORD: webtrocas